#!/bin/bash

### Packages
sudo apt update && sudo apt -y full-upgrade && sudo apt -y autoremove
sudo apt -y install chromium chromium-l10n libreoffice libreoffice-l10n-fr flameshot npm gimp okular evince
sudo apt update && sudo apt -y full-upgrade && sudo apt -y autoremove && sudo aptitude autoclean && sudo aptitude purge

